moneyex:
  business:
    - 'CAMBIAFX_,tc_compra : ,tc_venta : ,.'
    - 'TUCAMBISTA_,"buyExchangeRate": ,"sellExchangeRate": ,.'
    - 'CAMBISTAINKA_,"nTCCompra":","nTCVenta":",.'
    - 'ACOMO_,"BID":,"OFFER":,.'
    - 'CAMBIOSEGURO_,compra: ,venta: ,.'
    - 'TKAMBIO_,sell_type_change":",buy_type_change":",.'
    - 'REXTIE_,fx_rate_buy":",fx_rate_sell":",.'
    - 'DOLLARHOUSE_,buy-exchange-rate">,sell-exchange-rate">,.'
  server:
    type: WINDOWS
    pathBase: E:\iNovaStudio\Development\MoneyExchange\exchangeRates\
    pathUpdated: E:\iNovaStudio\Development\MoneyExchange\exchangeSaved\
  processDate: '18082020'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moneyexchange?serverTimezone=America/Santiago&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Q17f4r4qMP!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: none
api:
  common:
    version: 1.0.0
    title: Servicio
    description: Endpoints a ser consumidos por servicio-email
    termsOfServiceUrl: www.inovastudio.com/tocs
    license: Creative Commons
    licenseUrl: www.inovastudio.com
    contact:
      name: Hans Villaizan
      url: www.cooptumi.com
      email: aseniordesarrollo2@cooptumi.com
logging:
  level:
    org:
      apache:
        ibatis: TRACE
      springframework: WARN
mybatis:
  mapper-locations: classpath*:com/inovastudio/moneyex/mapper/*.xml
  type-aliases-package: com.inovastudio.moneyex.model
#spring:
#  datasource:
#    jndi-name: java:/erp-tumi
#  servlet:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB
#      enabled: true

