moneyex:
  business:
    - 'CAMBIAFX_,tc_compra : ,tc_venta : ,.'
    - 'TUCAMBISTA_,"buyExchangeRate": ,"sellExchangeRate": ,.'
    - 'CAMBISTAINKA_,"nTCCompra":","nTCVenta":",.'
    - 'ACOMO_,"BID":,"OFFER":,.'
    - 'CAMBIOSEGURO_,compra: ,venta: ,.'
    - 'TKAMBIO_,sell_type_change":",buy_type_change":",.'
    - 'REXTIE_,fx_rate_buy":",fx_rate_sell":",.'
    - 'DOLLARHOUSE_,buy-exchange-rate">,sell-exchange-rate">,.'
  server:
    type: WINDOWS
    pathBase: E:\iNovaStudio\Development\MoneyExchange\exchangeRates\
    pathUpdated: E:\iNovaStudio\Development\MoneyExchange\exchangeSaved\
  processDate: '10082020'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moneyexchange?serverTimezone=America/Santiago&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Q17f4r4qMP!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: none
